version: "3.1"
services:



   
  backend-service:
    image: rymabensalah/backend
    ports:
      - "8088:8089"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql_2:3306/ProjetDevops?autoReconnect=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    networks:
      - ci-network
    depends_on:
      - mysqldb
    
  mysqldb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ProjetDevops
   
    networks:
      - ci-network

networks:
  ci-network: