version: "2.2"
services:
  
#  
#  Sonarqube:
#    image: sonarqube:8.9.7-community
#    ports:
#      - "9000:9000"
#   
#    volumes:
#      - 'sonarQube_data:/opt/SonarQube/data'
#      - 'sonarQube_extensions:/opt/SonarQube/extensions'
#      - 'sonarQube_logs:/opt/SonarQube/logs'
#  
#  nexus:
#    image: sonatype/nexus3
#    ports:
#      - "8081:8081"
#    volumes:
#      - "nexus-data:/sonatype-work"
#
#  volumes :
#    sonarQube_data:
#    sonarQube_extensions:
#    sonarQube_logs:
#    nexus-data:
#  
  
  
  devopsproject:
 
    build: .
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://3306:3306/tpachato?autoReconnect=true&useSSL=false
     
  